### ISSUE TITLE
"405 Method Not Allowed" when trying to create new song

### ISSUE THREAD

**Issue by mjkaye** [jaitaiwan/CPresent#30]
On a fresh install (a couple of days ago), trying to save a new song results in the following error:

```
PUT http://127.0.0.1:8080/songs 405 Method Not Allowed
```

**Comment by jaitaiwan** [comment]
Hey Michael,

Thought I'd update the ticket and see if I can get your attention to see
how you're going with CPresent.

Kind Regards,

Daniel J Holmes
