### ISSUE TITLE
Not working with latest Node Modules on April 5, 2015

### ISSUE THREAD

**Issue by gcsizemore** [jaitaiwan/CPresent#31]
Had to specify modules in package.json as shown below:

{
  "name": "CPresent",
  "version": "1.0.0rc6",
  "description": "Simplified, web-based church presentation system.",
  "main": "index.js",
  "dependencies": {
    "express": "4.11.2",
    "mongojs": "latest",
    "mongodb": "latest",
    "socket.io": "1.2.1",
    "connect-compiler": "latest",
    "stylus": "0.49.3",
    "body-parser": "1.11.0",
    "serve-index": "^1.0.1",
    "serve-static": "^1.0.4"
  },
  "devDependencies": {
    "coffee-script": "1.9.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/jaitaiwan/CPresent"
  },
  "keywords": [
    "church",
    "presentation",
    "angularjs"
  ],
  "author": "Daniel J Holmes",
  "license": "BSD"
}

**Comment by gcsizemore** [comment]
I'm using RHEL 7 / Node 0.10.33

**Comment by jaitaiwan** [comment]
Thanks! Love to know what you're using CPresent for and where! Also feel
free to create a pull request against the package.json

Kind Regards,

Daniel J Holmes

**Comment by jaitaiwan** [comment]
@gcsizemore looking to get this package updated fairly soon. Can I ask where you're using this?

**Comment by jaitaiwan** [comment]
Working in latest master now
